dist: trusty
sudo: required
language: c
compiler: gcc
script: scripts/gen_appimage.sh
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "*.AppImage"
  file_glob: true
  skip_cleanup: true
